// src/js/RadialProgress.jsx
import React from 'react';
import PropTypes from 'prop-types';


export default function RadialProgress({ value }) {
  const valueFormatted = parseInt(value, 10);
  const radius = 28;
  const trackWidth = 1;
  const valueWidth = 3;

  const size = (radius * 2) + Math.max(valueWidth, trackWidth);
  const center = size / 2;
  const cicumference = 2 * Math.PI * radius;

  const valueStyle = {
    strokeDashoffset: cicumference * (1 - (value / 100)),
    strokeDasharray: cicumference,
  };

  return (
    <div className="progress-circle">
      <span className="value flex-center">{valueFormatted}</span>
      <svg className="progress-svg" width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
        <circle className="track" cx={center} cy={center} r={radius} strokeWidth={trackWidth} />
        <circle className="value" cx={center} cy={center} r={radius} strokeWidth={valueWidth} style={valueStyle} />
      </svg>
    </div>
  );
}


RadialProgress.propTypes = {
  value: PropTypes.string.isRequired,
};

// src/components/widgets/RadialProgress.vue
<template>
  <div class="svg-widget radial-progress">
    <span class="value flex-center">{{ valueFormatted }}</span>
    <svg :width="size" :height="size" :view-box="`0 0 ${size} ${size}`">
      <circle class="track" :cx="center" :cy="center" :r="radius" :stroke-width="trackWidth" />
      <circle class="value" :cx="center" :cy="center" :r="radius" :stroke-width="valueWidth" :style="valueStyle" />
    </svg>
  </div>
</template>

<script>
export default {
  name: "radial-progress",
  data() {
    const radius = 28;
    const trackWidth = 2;
    const valueWidth = 3;

    const size = (radius * 2) + Math.max(valueWidth, trackWidth);
    const center = size / 2;
    const circumference = 2 * Math.PI * radius;

    return {
      size,
      center,
      radius,
      circumference,
      trackWidth,
      valueWidth,
    };
  },
  computed: {
    valueFormatted() {
      const valueFormatted = parseInt(this.value, 10);
      return Number.isNaN(valueFormatted) ? "-" : valueFormatted;
    },
    valueStyle() {
      return {
        strokeDashoffset: this.circumference * (1 - (this.value / 100)),
        strokeDasharray: this.circumference,
      };
    },
  },
  props: {
    value: [Number, String],
  },
};
</script>
