// src/components/ConnectionIndicator.vue
<template>
  <div :class="`status-${connectionStatus} ${className()}`">
    <Icon :name="iconName()" />
  </div>
</template>

<script>
import { mapState } from "vuex";
import Icon from "@/components/Icon.vue";

export default {
  name: "connection-indicator",
  components: {
    Icon,
  },
  methods: {
    iconName() {
      return this.connectionStatus === "connected" ? "signal" : "signal-off";
    },
    className() {
      return this.connectionStatus === "connecting" ? "pulse-opacity" : "";
    },
  },
  computed: {
    ...mapState(["config", "connectionStatus"]),
  },
};
</script>

// src/js/ConnectionIndicator.jsx
import React from 'react';
import { connect } from 'react-redux';
import PropTypes from 'prop-types';

import { Record } from 'immutable';
import { stateToProps } from './utilities';

import Icon from './Icon';


function ConnectionIndicator({ connection }) {
  let iconName = 'signal-off';
  let className = '';
  if (connection.status === 'connected') {
    iconName = 'signal';
  } else if (connection.status === 'connecting') {
    className = 'pulse-opacity';
  }

  return (
    <div className={`status-${connection.status} ${className}`}>
      <Icon name={iconName} />
    </div>
  );
}

ConnectionIndicator.propTypes = {
  connection: PropTypes.instanceOf(Record).isRequired,
};

export default connect(stateToProps('connection'))(ConnectionIndicator);
